
//TopDownGameMode.
#include "UnitBase.h"
#include "TopDownGameMode.h"
#include "MyPlayerController.h"
#include "Brawler.h"
#include "TopDownCameraPawn.h"
#include "GridTile.h"
#include "Sniper.h"
#include "GameFramework/Actor.h"
#include "Engine/World.h"
#include "UIManager.h"
#include "Blueprint/UserWidget.h"
#include "UObject/ConstructorHelpers.h"
#include "EngineUtils.h" // Aggiunto per usare TActorIterator


ATopDownGameMode::ATopDownGameMode()
{
	PlayerControllerClass = AMyPlayerController::StaticClass();


	DefaultPawnClass = ATopDownCameraPawn::StaticClass();
	SelectedUnitType = EUnitType::Brawler; // Default
	PrimaryActorTick.bCanEverTick = true;

	// üîπ Carica la classe del widget UI
	static ConstructorHelpers::FClassFinder<UUIManager> UIManagerBPClass(TEXT("/Game/UI/WBP_CharacterSelection"));
	if (UIManagerBPClass.Succeeded())
	{
		UIManagerClass = UIManagerBPClass.Class;
		UE_LOG(LogTemp, Warning, TEXT("‚úÖ UIManagerClass caricato correttamente!"));
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("‚ùå UIManagerClass non trovato! Controlla il percorso."));
	}
}

void ATopDownGameMode::BeginPlay()
{
	Super::BeginPlay();
	

	APlayerController* PC = GetWorld()->GetFirstPlayerController();
	if (PC)
	{
		PC->bShowMouseCursor = true;
		PC->bEnableClickEvents = true;
		PC->bEnableMouseOverEvents = true;

		PC->InputComponent->BindAction("LeftClick", IE_Pressed, this, &ATopDownGameMode::OnGridClicked);
	}
	UE_LOG(LogTemp, Warning, TEXT("üî• TopDownGameMode::BeginPlay() chiamato!"));

	if (!UIManagerClass)
	{
		UE_LOG(LogTemp, Error, TEXT("‚ùå UIManagerClass non √® impostato nel GameMode!"));
		return;
	}

	UIManagerInstance = CreateWidget<UUIManager>(GetWorld(), UIManagerClass);
	if (!UIManagerInstance)
	{
		UE_LOG(LogTemp, Error, TEXT("‚ùå UIManager non √® stato creato!"));
		return;
	}

	UIManagerInstance->AddToViewport();
	UE_LOG(LogTemp, Warning, TEXT("‚úÖ UIManager: Widget creato con successo!"));
}


void ATopDownGameMode::SelectUnit(EUnitType UnitType)
{
	if (UnitType == EUnitType::Brawler)
	{
		if (bBrawlerSelected) // Controlla se √® gi√† stato selezionato
		{
			UE_LOG(LogTemp, Warning, TEXT("‚ö†Ô∏è Brawler gi√† posizionato, non puoi selezionarlo di nuovo!"));
			return;
		}
		UE_LOG(LogTemp, Warning, TEXT("‚úÖ Unit√† selezionata: Brawler"));
	}
	else if (UnitType == EUnitType::Sniper)
	{
		if (bSniperSelected) // Controlla se √® gi√† stato selezionato
		{
			UE_LOG(LogTemp, Warning, TEXT("‚ö†Ô∏è Sniper gi√† posizionato, non puoi selezionarlo di nuovo!"));
			return;
		}
		UE_LOG(LogTemp, Warning, TEXT("‚úÖ Unit√† selezionata: Sniper"));
	}
    
	SelectedUnitType = UnitType;
}



void ATopDownGameMode::PlaceUnit(EUnitType UnitType, FVector Location, AGridTile* ClickedTile)
{
    if (!ClickedTile)
    {
        UE_LOG(LogTemp, Error, TEXT("‚ùå ClickedTile non valido in PlaceUnit!"));
        return;
    }

    // üîπ Verifica se la cella √® un ostacolo
    if (ClickedTile->bIsObstacle)
    {
        UE_LOG(LogTemp, Warning, TEXT("‚ö†Ô∏è Tentativo di piazzare un'unit√† su un ostacolo alla cella (%d, %d), operazione annullata!"), ClickedTile->XIndex, ClickedTile->YIndex);
        return; // ‚õî Evita di segnare l'unit√† come posizionata
    }

    UE_LOG(LogTemp, Warning, TEXT("üî• Tentativo di piazzare un'unit√† sulla cella (%d, %d)!"), ClickedTile->XIndex, ClickedTile->YIndex);

    if ((UnitType == EUnitType::Brawler && bBrawlerPlaced) ||
        (UnitType == EUnitType::Sniper && bSniperPlaced))
    {
        UE_LOG(LogTemp, Warning, TEXT("‚ö†Ô∏è Questa unit√† √® gi√† stata posizionata e non pu√≤ essere piazzata di nuovo!"));
        return;
    }

    // ‚úÖ Centra il posizionamento dell'unit√† nella cella
	FVector SpawnLocation = ClickedTile->GetActorLocation();
	SpawnLocation.Z += 50;


    FRotator SpawnRotation = FRotator::ZeroRotator;

    UWorld* World = GetWorld();
    if (!World) return;

	if (UnitType == EUnitType::Brawler)
	{
		ABrawler* Brawler = World->SpawnActor<ABrawler>(ABrawler::StaticClass(), SpawnLocation, SpawnRotation);
		if (Brawler)
		{
			BrawlerInstance = Brawler; // üî¥ Memorizza l'istanza
			bBrawlerPlaced = true;
			bBrawlerSelected = true;
			
			UE_LOG(LogTemp, Warning, TEXT("üéÆ Brawler posizionato sulla griglia!"));
		}
	}
	else if (UnitType == EUnitType::Sniper)
	{
		ASniper* Sniper = World->SpawnActor<ASniper>(ASniper::StaticClass(), SpawnLocation, SpawnRotation);
		if (Sniper)
		{
			SniperInstance = Sniper; // üî¥ Memorizza l'istanza
			bSniperPlaced = true;
			bSniperSelected = true;
			UE_LOG(LogTemp, Warning, TEXT("üéÆ Sniper posizionato sulla griglia!"));
		}
	}

	UE_LOG(LogTemp, Warning, TEXT("üìå Stato bIsBlocked della cella di piazzamento (%d, %d): %s"),
		ClickedTile->XIndex, ClickedTile->YIndex, ClickedTile->bIsBlocked ? TEXT("TRUE") : TEXT("FALSE"));

    // üî¥ **NON CHIAMARE** ClickedTile->SetUnitMaterial(UnitType);
}



void ATopDownGameMode::OnGridClicked()
{
	APlayerController* PC = GetWorld()->GetFirstPlayerController();
	if (!PC) return;

	FHitResult Hit;
	PC->GetHitResultUnderCursor(ECollisionChannel::ECC_Visibility, false, Hit);

	if (Hit.bBlockingHit)
	{
		AUnitBase* ClickedUnit = Cast<AUnitBase>(Hit.GetActor());
		if (ClickedUnit)
		{
			UE_LOG(LogTemp, Warning, TEXT("üñ±Ô∏è Hai cliccato sull'unit√†: %s"), *ClickedUnit->GetName());

			if (ClickedUnit->IsA(ABrawler::StaticClass()))
			{
				bBrawlerSelected = true;
				HighlightMovementRange(ClickedUnit, Cast<ABrawler>(ClickedUnit)->GetMovementRange(), true);
			}
			else if (ClickedUnit->IsA(ASniper::StaticClass()))
			{
				bSniperSelected = true;
				HighlightMovementRange(ClickedUnit, Cast<ASniper>(ClickedUnit)->GetMovementRange(), true);
			}

			return; // ‚õî Interrompi qui, cos√¨ non viene processato come clic su cella
		}

		AGridTile* ClickedTile = Cast<AGridTile>(Hit.GetActor());
		if (!ClickedTile) return;

		// ‚úÖ Se sto piazzando il Brawler
		if (SelectedUnitType == EUnitType::Brawler && !bBrawlerPlaced)
		{
			PlaceUnit(EUnitType::Brawler, ClickedTile->GetActorLocation(), ClickedTile);
			return;
		}

		// ‚úÖ Se sto piazzando lo Sniper
		if (SelectedUnitType == EUnitType::Sniper && !bSniperPlaced)
		{
			PlaceUnit(EUnitType::Sniper, ClickedTile->GetActorLocation(), ClickedTile);
			return;
		}

		// üîπ Se clicco di nuovo sul Brawler gi√† posizionato
		if (BrawlerInstance && ClickedTile == GetTileAtWorldPosition(BrawlerInstance->GetActorLocation()))
		{
			UE_LOG(LogTemp, Warning, TEXT("üñ±Ô∏è Brawler selezionato! Blocco il percorso."));
			bBrawlerSelected = true;
			HighlightMovementRange(BrawlerInstance, BrawlerInstance->GetMovementRange(), true);
			return;
		}

		// üîπ Se clicco di nuovo sullo Sniper gi√† posizionato
		if (SniperInstance && ClickedTile == GetTileAtWorldPosition(SniperInstance->GetActorLocation()))
		{
			UE_LOG(LogTemp, Warning, TEXT("üñ±Ô∏è Sniper selezionato! Blocco il percorso."));
			bSniperSelected = true;
			HighlightMovementRange(SniperInstance, SniperInstance->GetMovementRange(), true);
			return;
		}

		// ‚úÖ Se un'unit√† √® selezionata e ho cliccato una cella evidenziata
		if (bBrawlerSelected && BrawlerInstance && HighlightedTiles.Contains(ClickedTile))
		{
			MoveUnit(BrawlerInstance, ClickedTile);
			return;
		}
		if (bSniperSelected && SniperInstance && HighlightedTiles.Contains(ClickedTile))
		{
			MoveUnit(SniperInstance, ClickedTile);
			return;
		}
	}
}




void ATopDownGameMode::HighlightMovementRange(AActor* Unit, int Range, bool bHighlight)
{
    if (!Unit) return;

    // üîÅ Pulizia precedente (reset)
    if (!bHighlight)
    {
        for (AGridTile* Tile : HighlightedTiles)
        {
            if (Tile)
            {
                Tile->SetHighlight(false);
                Tile->bIsBlocked = false;
                //UE_LOG(LogTemp, Warning, TEXT("üîì Cella sbloccata: (%d, %d)"), Tile->XIndex, Tile->YIndex);
            }
        }
        HighlightedTiles.Empty();
        return;
    }

    FVector UnitLocation = Unit->GetActorLocation();
    AGridTile* StartTile = this->GetTileAtWorldPosition(UnitLocation);

    if (!StartTile)
    {
        UE_LOG(LogTemp, Error, TEXT("‚ùå StartTile non valido!"));
        return;
    }

    StartTile->bIsBlocked = true;
   // UE_LOG(LogTemp, Warning, TEXT("üîí Cella iniziale bloccata: (%d, %d)"), StartTile->XIndex, StartTile->YIndex);

    int32 MaxSteps = Range;
    TQueue<TPair<AGridTile*, int32>> TileQueue;
    TSet<AGridTile*> VisitedTiles;

    TileQueue.Enqueue(TPair<AGridTile*, int32>(StartTile, 0));
    VisitedTiles.Add(StartTile);

    while (!TileQueue.IsEmpty())
    {
        TPair<AGridTile*, int32> CurrentPair;
        TileQueue.Dequeue(CurrentPair);

        AGridTile* CurrentTile = CurrentPair.Key;
        int32 Steps = CurrentPair.Value;

        if (CurrentTile && Steps <= MaxSteps)
        {
            CurrentTile->SetHighlight(true);
            HighlightedTiles.Add(CurrentTile);
            //UE_LOG(LogTemp, Warning, TEXT("üîÜ Highlight su (%d, %d) ‚Äî Bloccata: %s"), CurrentTile->XIndex, CurrentTile->YIndex, CurrentTile->bIsBlocked ? TEXT("TRUE") : TEXT("FALSE"));

            if (Steps >= MaxSteps) continue;

            TArray<AGridTile*> Neighbors;
            Neighbors.Add(GetTileAt(CurrentTile->XIndex + 1, CurrentTile->YIndex));
            Neighbors.Add(GetTileAt(CurrentTile->XIndex - 1, CurrentTile->YIndex));
            Neighbors.Add(GetTileAt(CurrentTile->XIndex, CurrentTile->YIndex + 1));
            Neighbors.Add(GetTileAt(CurrentTile->XIndex, CurrentTile->YIndex - 1));

            for (AGridTile* Neighbor : Neighbors)
            {
                if (Neighbor && !Neighbor->bIsObstacle && !Neighbor->bIsBlocked && !VisitedTiles.Contains(Neighbor))
                {
                    TileQueue.Enqueue(TPair<AGridTile*, int32>(Neighbor, Steps + 1));
                    VisitedTiles.Add(Neighbor);
                    UE_LOG(LogTemp, Warning, TEXT("‚úÖ Cella libera aggiunta: (%d, %d)"), Neighbor->XIndex, Neighbor->YIndex);
                }
                else if (Neighbor && Neighbor->bIsBlocked)
                {
                    UE_LOG(LogTemp, Warning, TEXT("‚õîÔ∏è Cella gi√† bloccata ignorata: (%d, %d)"), Neighbor->XIndex, Neighbor->YIndex);
                }
                else if (Neighbor && Neighbor->bIsObstacle)
                {
                    UE_LOG(LogTemp, Warning, TEXT("üöß Cella ostacolo ignorata: (%d, %d)"), Neighbor->XIndex, Neighbor->YIndex);
                }
            }
        }
    }
}





AGridTile* ATopDownGameMode::GetTileAtWorldPosition(FVector WorldPosition)
{
	AGridTile* NearestTile = nullptr;
	float MinDistance = FLT_MAX;

	for (TActorIterator<AGridTile> It(GetWorld()); It; ++It)
	{
		float Distance = FVector::Dist(It->GetActorLocation(), WorldPosition);
        
		if (Distance < MinDistance)
		{
			MinDistance = Distance;
			NearestTile = *It;
		}
	}

	if (NearestTile)
	{
		UE_LOG(LogTemp, Warning, TEXT("üìå Trovata cella pi√π vicina a (%s) ‚Üí (%d, %d)"), 
			*WorldPosition.ToString(), NearestTile->XIndex, NearestTile->YIndex);
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("‚ùå Nessuna cella trovata vicino a (%s)!"), *WorldPosition.ToString());
	}

	return NearestTile;
}








AGridTile* ATopDownGameMode::GetTileAt(int32 X, int32 Y)
{
	for (TActorIterator<AGridTile> It(GetWorld()); It; ++It)
	{
		if (It->XIndex == X && It->YIndex == Y)
		{
			return *It;
		}
	}
	return nullptr;
}

void ATopDownGameMode::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	APlayerController* PC = GetWorld()->GetFirstPlayerController();
	if (!PC) return;

	FHitResult Hit;
	PC->GetHitResultUnderCursor(ECollisionChannel::ECC_Visibility, false, Hit);

	if (Hit.bBlockingHit)
	{
		//UE_LOG(LogTemp, Warning, TEXT("üéØ Oggetto sotto il mouse: %s"), *Hit.GetActor()->GetName());
	}
}

void ATopDownGameMode::MoveUnit(AActor* Unit, AGridTile* TargetTile)
{
	if (!Unit || !TargetTile) return;

	AGridTile* StartTile = GetTileAtWorldPosition(Unit->GetActorLocation());
	if (!StartTile)
	{
		UE_LOG(LogTemp, Error, TEXT("‚ùå Nessuna cella di partenza trovata!"));
		return;
	}

	// Algoritmo per trovare il percorso pi√π corto (BFS)
	TQueue<TPair<AGridTile*, int32>> TileQueue;
	TMap<AGridTile*, AGridTile*> CameFrom;
    
	TileQueue.Enqueue(TPair<AGridTile*, int32>(StartTile, 0));
	CameFrom.Add(StartTile, nullptr);

	while (!TileQueue.IsEmpty())
	{
		TPair<AGridTile*, int32> CurrentPair;
		TileQueue.Dequeue(CurrentPair);

		AGridTile* CurrentTile = CurrentPair.Key;

		if (CurrentTile == TargetTile)
		{
			// Abbiamo trovato il percorso pi√π breve, ricostruiamolo
			TArray<AGridTile*> Path;
			AGridTile* Step = TargetTile;
			while (Step)
			{
				Path.Insert(Step, 0);
				Step = CameFrom[Step];
			}

			// Muove l'unit√† lungo il percorso
			MoveAlongPath(Unit, Path);
			return;
		}

		TArray<AGridTile*> Neighbors;
		Neighbors.Add(GetTileAt(CurrentTile->XIndex + 1, CurrentTile->YIndex));
		Neighbors.Add(GetTileAt(CurrentTile->XIndex - 1, CurrentTile->YIndex));
		Neighbors.Add(GetTileAt(CurrentTile->XIndex, CurrentTile->YIndex + 1));
		Neighbors.Add(GetTileAt(CurrentTile->XIndex, CurrentTile->YIndex - 1));

		for (AGridTile* Neighbor : Neighbors)
		{
			if (Neighbor && !Neighbor->bIsObstacle && !CameFrom.Contains(Neighbor))
			{
				TileQueue.Enqueue(TPair<AGridTile*, int32>(Neighbor, CurrentPair.Value + 1));
				CameFrom.Add(Neighbor, CurrentTile);
			}
		}
	}

	UE_LOG(LogTemp, Warning, TEXT("‚ùå Nessun percorso trovato!"));
}

void ATopDownGameMode::MoveAlongPath(AActor* Unit, const TArray<AGridTile*>& Path)
{
	if (!Unit || Path.Num() == 0) return;

	AUnitBase* RealUnit = Cast<AUnitBase>(Unit);
	if (RealUnit)
	{
		RealUnit->StartMovingAlongPath(Path);
	}

	// Dopo aver avviato il movimento, resettiamo gli highlight
	HighlightMovementRange(Unit, 0, false);

	if (Unit->IsA(ABrawler::StaticClass()))
	{
		bBrawlerSelected = false;
	}
	else if (Unit->IsA(ASniper::StaticClass()))
	{
		bSniperSelected = false;
	}
}



void ATopDownGameMode::HighlightMovableTiles(AUnitBase* Unit)
{
	if (!Unit) return;
	// TODO: Evidenzia celle intorno a Unit->CurrentTile
}
void ATopDownGameMode::MoveUnitAlongPath(AUnitBase* Unit, const TArray<AGridTile*>& Path)
{
	if (Unit)
	{
		Unit->MoveAlongPath(Path);
	}
}
void ATopDownGameMode::HandleUnitClicked(AUnitBase* ClickedUnit)
{
	if (!ClickedUnit) return;

	// Se √® un Brawler
	if (ClickedUnit == BrawlerInstance)
	{
		bBrawlerSelected = true;
		bSniperSelected = false;
		UE_LOG(LogTemp, Warning, TEXT("üñ±Ô∏è Brawler selezionato! Blocco il percorso."));
		HighlightMovementRange(BrawlerInstance, BrawlerInstance->GetMovementRange(), true);
	}

	// Se √® uno Sniper
	else if (ClickedUnit == SniperInstance)
	{
		bSniperSelected = true;
		bBrawlerSelected = false;
		UE_LOG(LogTemp, Warning, TEXT("üñ±Ô∏è Sniper selezionato! Blocco il percorso."));
		HighlightMovementRange(SniperInstance, SniperInstance->GetMovementRange(), true);
	}
}
void ATopDownGameMode::MoveStep()
{
	if (!MovingUnit || CurrentStepIndex >= MovementPath.Num())
	{
		GetWorld()->GetTimerManager().ClearTimer(MovementTimerHandle);

		// Spegni le celle illuminate dopo il movimento
		HighlightMovementRange(MovingUnit, 0, false);

		// Deseleziona l'unit√† dopo il movimento
		if (MovingUnit->IsA(ABrawler::StaticClass()))
			bBrawlerSelected = false;
		else if (MovingUnit->IsA(ASniper::StaticClass()))
			bSniperSelected = false;

		// Reset
		MovementPath.Empty();
		MovingUnit = nullptr;
		CurrentStepIndex = 0;
		return;
	}

	FVector TargetLocation = MovementPath[CurrentStepIndex]->GetActorLocation();
	TargetLocation.Z += 50;
	MovingUnit->SetActorLocation(TargetLocation);

	CurrentStepIndex++;
}
